server:
  servlet:
    context-path: /api
  port: 8080


deeseecomics:
  allowed-superpowers: strength,speed,flight,invulnerability,healing
  encryption:
    default-shift: 3
logging:
  level:
    root: debug