server:
  servlet:
    context-path: /api
  port: 8080

spring:
  jackson:
    default-property-inclusion: non_null

deeseecomics:
  allowed-superpowers: strength,speed,flight,invulnerability,healing
  encryption:
    default-shift: 3